name: Run Container Scan on Super Mario Docker Image with Quality Gate

on:
  push:
    branches:
      - master

jobs:
  run_container_image_scan_on_supermario_docker_image:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: docker.io/philemon22/training-repo:mario-game-1.0.0

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t $IMAGE_NAME .

      - name: Push Docker Image
        run: docker push $IMAGE_NAME

      - name: Save Docker Image as Tarball
        run: docker save $IMAGE_NAME -o supermariolatestdockerimage.tar

      - name: Run Trivy Vulnerability Scan
        uses: aquasecurity/trivy-action@master
        with:
          input: supermariolatestdockerimage.tar
          exit-code: '1'
          severity: 'CRITICAL,HIGH'
